version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: tuantv
      MYSQL_DATABASE: iam
      MYSQL_USER: tuantv1
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - E:\docker-storage:/var/lib/mysql
